spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon_db
    username: your_username
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: your_secret_key
